// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyCBcbtxZ_14AB36dyPyMeh1qWcQC2KGY',
    appId: '1:869084853519:android:7c7d955b69656586ba7a7a',
    messagingSenderId: '869084853519',
    projectId: 'chat-app-328af',
    storageBucket: 'chat-app-328af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2FW5zh6SLS5CfsOL00GvDPe-L4S6DQOU',
    appId: '1:869084853519:ios:27facc385d504d0fba7a7a',
    messagingSenderId: '869084853519',
    projectId: 'chat-app-328af',
    storageBucket: 'chat-app-328af.appspot.com',
    androidClientId: '869084853519-lbtcstqor5bdjgto135t7qedss833oul.apps.googleusercontent.com',
    iosClientId: '869084853519-5um9uboc3dr6gcc4bur8nt17ciu0r3on.apps.googleusercontent.com',
    iosBundleId: 'com.example.youChat',
  );
}
